### ISSUE TITLE
ERROR: Unsatisfiable requirements detected for package FreqTables

### ISSUE THREAD

**Issue by skanskan** [JuliaPlots/StatsMakie.jl#44]
StatsMakie asks for FreqTables 0.3.1 but the latest master version is 0.3.0:
```
ERROR: Unsatisfiable requirements detected for package FreqTables [da1fdf0e]:
 FreqTables [da1fdf0e] log:
 ├─possible versions are: 0.3.0 or uninstalled
 ├─restricted to versions 0.3.1-* by StatsMakie [9d48ccf0] — no versions left
 │ └─StatsMakie [9d48ccf0] log:
 │   ├─possible versions are: 0.0.0 or uninstalled
 │   └─StatsMakie [9d48ccf0] is fixed to version 0.0.0
 └─FreqTables [da1fdf0e] is fixed to version 0.3.0+
```

**Comment by piever** [comment]
FreqTables 0.3.1 was released a few day ago: https://github.com/JuliaLang/METADATA.jl/pull/19736

You may need to run `pkg> up` to update the registry and have the release available (maybe also `pkg> free FreqTables` to avoid being on master or on a devved version).

**Comment by SimonDanisch** [comment]
That should fix it! Feel free to reopen if not ;)

**Comment by skanskan** [comment]
I tried freeing, updating...  but still the same error.
At the end I had to hack the REQUIRE file, I've changed FreqTables version to 0.3.0 and now it works, though I guess this is not a good idea :)
